export const LIST_ALL = 'LIST_ALL'; // do là const nên phải viết hoa hết tên biến
export const ADD_TASK = 'ADD_TASK';
export const IS_DISPLAY_FORM = 'IS_DISPLAY_FORM';
export const CLOSE_FORM = 'CLOSE_FORM';
export const OPEN_FORM = 'OPEN_FORM';
export const UPDATE_STATUS = 'UPDATE_STATUS';
export const DELETE_TASK = 'DELETE_TASK';
export const UPDATE_TASK = 'UPDATE_TASK';
export const FILTER_TABLE = 'FILTER_TABLE';
export const SEARCH_NAME = 'SEARCH_NAME';
export const SORT = 'SORT';